body = "#ai retargeting #technology #startup; #advertising"
created_at = "2018-02-07T20:19:08.534Z"
is_approved = true
job_board_url = "https://www.simplaex.com/careers/"
latitude = 52.5084583
longitude = 13.3786549
slug = "simplaex"
tags = ["ai", "technology", "startup", "advertising"]
title = "Simplaex"
updated_at = "2019-06-16T10:36:09.730Z"
