body = "#startup #job-board #tech"
created_at = "2017-06-28T20:19:25.379Z"
is_approved = true
job_board_url = "http://berlinstartupjobs.com"
slug = "berlin-startup-jobs"
tags = ["startup", "job-board", "tech"]
title = "Berlin startup jobs"
updated_at = "2019-06-16T10:36:09.731Z"
