body = "online #media for #football; #startup"
created_at = "2018-02-03T18:15:24.172Z"
is_approved = true
job_board_url = "https://company.onefootball.com/careers"
latitude = 52.5321581
longitude = 13.4270269
slug = "onefootball"
tags = ["media", "football", "startup"]
title = "Onefootball"
updated_at = "2019-06-16T10:36:09.730Z"
