body = "#coworking spaces in Germany"
created_at = "2019-05-12T09:29:52.000Z"
is_approved = true
job_board_url = "https://www.designoffices.de/karriere/jobs/jobboerse/"
slug = "design-offices"
tags = ["coworking"]
title = "Design Offices"
updated_at = "2019-06-16T10:44:09.000Z"
