body = "online #printing service"
created_at = "2017-06-28T20:33:33.753Z"
is_approved = true
job_board_url = "https://karriere.flyeralarm.com/jobs"
latitude = 52.511088
longitude = 13.2858871
slug = "flyeralarm"
tags = ["printing"]
title = "FlyerAlarm"
updated_at = "2019-06-16T10:36:09.783Z"
