created_at = "2018-02-01T11:59:44.588Z"
is_approved = true
job_board_url = "https://jobs.getgrover.com/"
latitude = 52.5143621
longitude = 13.4214494
slug = "grover"
tags = []
title = "Grover"
updated_at = "2019-06-16T10:36:08.532Z"
