body = "#ecommerce #startup conecting customers and companies ; #b2c"
created_at = "2017-06-28T20:33:25.404Z"
is_approved = true
job_board_url = "http://unternehmen.kaeuferportal.de/karriere/stellenangebote"
latitude = 52.5087788
longitude = 13.3756564
slug = "kaeuferportal"
tags = ["ecommerce", "startup", "b2c"]
title = "Kaeuferportal"
updated_at = "2019-06-16T10:36:09.728Z"
