body = "candidate driven #technology #job-board"
created_at = "2018-02-05T21:50:58.966Z"
is_approved = true
job_board_url = "https://landing.jobs/jobs?city_search=Berlin&country=DE"
slug = "landingjobs"
tags = ["technology", "job-board"]
title = "Landing.jobs"
updated_at = "2019-06-16T10:36:08.529Z"
