body = "PUREGANIC stands for sustainable and natural nutritional supplements adapted to your individual needs. We have developed an intelligent algorithm that uses up-to-date scientific data and the ability to individually and meaningfully combine herbal ingredients with a very high nutrient content, so you can easily and naturally supplement your diet to meet your nutritional goals. #food #nutrition #startup"
created_at = "2019-08-01T09:52:06.761Z"
is_approved = true
job_board_url = "https://pureganic.de"
slug = "pureganic"
tags = ["food", "nutrition", "startup"]
title = "Pureganic"
