body = "#communication and #pr #agency"
created_at = "2017-06-28T20:36:34.670Z"
is_approved = true
job_board_url = "https://www.zucker-kommunikation.de/jobs/"
latitude = 52.53019
longitude = 13.40325
slug = "zucker-kommunikation"
tags = ["communication", "pr", "agency"]
title = "Zucker Kommunikation:"
updated_at = "2019-06-16T10:36:09.629Z"
