body = "Insurance #startup"
created_at = "2019-04-11T09:34:04.273Z"
is_approved = true
job_board_url = "https://wefox-jobs.personio.de"
job_board_provider = "personio"
job_board_hostname = "wefox-jobs"
latitude = 52.4882045
longitude = 13.4229545
slug = "wefox"
tags = ["startup"]
title = "wefox"
updated_at = "2019-06-16T10:36:08.532Z"
