body = "Volders helps users #monitoring their #personal #contracts, such as mobile phone, electricity or gym, from everywhere at any time. Before your contracts are automatically renewed, users are given the option to terminate, prolong or switch contracts via a simple and straightforward process"
created_at = "2017-06-28T20:32:00.892Z"
is_approved = true
job_board_url = "https://www.volders.de/karriere"
latitude = 52.502278
longitude = 13.40785
slug = "volders"
tags = ["monitoring", "personal", "contracts"]
title = "Volders"
updated_at = "2019-06-16T10:36:08.537Z"
