body = "#creative #tech and #general job #newsletter"
created_at = "2017-06-28T20:22:18.848Z"
is_approved = true
job_board_url = "http://www.woloho.com"
slug = "woloho"
tags = ["creative", "tech", "general", "newsletter"]
title = "Woloho"
updated_at = "2019-06-16T10:36:08.535Z"
